import {chromium,webkit} from 'playwright';
const ORIGIN='http://127.0.0.1:4173';
async function seedLegacy(page){
  await page.goto(`${ORIGIN}/fixtures/recognition/clean-fixture-001/envelope.json`,{waitUntil:'domcontentloaded'});
  await page.evaluate(async()=>{
    const res=await fetch('/fixtures/recognition/clean-fixture-001/source.png'),buf=await res.arrayBuffer(),bytes=new Uint8Array(buf),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');
    const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('record-foundation',1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('games'))d.createObjectStore('games',{keyPath:'id'});if(!d.objectStoreNames.contains('pages')){const s=d.createObjectStore('pages',{keyPath:'id'});s.createIndex('gameId','gameId');}if(!d.objectStoreNames.contains('settings'))d.createObjectStore('settings',{keyPath:'key'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
    const start='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',after='rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1',t='2026-09-01T00:00:00.000Z',game={id:'legacy-browser-game1',schema:'record-game/1',createdAt:t,updatedAt:t,state:'CERTIFIED',metadata:{event:'Legacy Browser Fixture',site:'',date:'2026.09.01',round:'1',board:'',section:'',white:'',black:'',result:'*',timeControl:'90+30'},startFen:start,sans:['e4'],plies:[{ply:1,san:'e4',before:start,after,provenance:'USER_ENTERED',sourceRef:null}],notes:'legacy',certification:{legacy:true}},source={id:'legacy-browser-page1',gameId:game.id,order:0,createdAt:t,name:'legacy.png',mime:'image/png',size:bytes.length,sha256:hash,blob:new Blob([bytes],{type:'image/png'})};
    await new Promise((resolve,reject)=>{const tx=db.transaction(['games','pages'],'readwrite');tx.objectStore('games').put(game);tx.objectStore('pages').put(source);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();
  });
}
async function migrationGate(type,name){const browser=await type.launch({headless:true}),context=await browser.newContext(),page=await context.newPage();await seedLegacy(page);await page.goto(`${ORIGIN}/`,{waitUntil:'networkidle'});await page.getByRole('button',{name:'LIBRARY'}).click();await page.getByText('Legacy Browser Fixture',{exact:true}).waitFor();await page.getByText(/1 plies/).waitFor();await page.getByRole('button',{name:/Legacy Browser Fixture/}).click();await page.getByText(/CERTIFICATION INVALIDATED|READY_FOR_REVIEW/).first().waitFor();await browser.close();console.log(`${name} actual v0.1→v0.3 browser migration PASS`);}
async function appGate(type,name){const browser=await type.launch({headless:true});const context=await browser.newContext({acceptDownloads:true});const page=await context.newPage();await page.goto(`${ORIGIN}/`,{waitUntil:'networkidle'});await page.getByRole('button',{name:/NEW RECORD/}).click();await page.locator('input[type=file]').setInputFiles('fixtures/recognition/clean-fixture-001/source.png');await page.getByText('Page 1',{exact:true}).waitFor();await page.getByRole('button',{name:'RECOGNIZE'}).click();await page.getByText(/Recognition: COMPLETE/).waitFor();await page.getByRole('button',{name:'GAME RECORD'}).click();await page.getByRole('button',{name:'ENTER SAN'}).click();await page.getByLabel('Move').fill('e4');await page.getByRole('button',{name:'ADD MOVE'}).click();await page.getByText('e4',{exact:true}).waitFor();await page.getByRole('button',{name:/REVIEW \/ CERTIFY/}).click();await page.getByRole('button',{name:'CERTIFY CURRENT RECORD'}).click();await page.getByText(/Certification status: VALID/).waitFor();await page.getByRole('button',{name:'MARK UNREADABLE'}).first().click();await page.getByText(/Certification status: INVALIDATED/).waitFor();await page.getByRole('button',{name:'CERTIFY CURRENT RECORD'}).click();await page.getByRole('status').filter({hasText:/REC-CERT-006: Record is explicitly marked as needing review\./}).waitFor();await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:'LIBRARY'}).click();await page.getByText(/1 plies/).waitFor();await page.getByRole('button',{name:'HOME'}).click();await context.setOffline(true);await page.reload({waitUntil:'domcontentloaded'});await page.getByText('RECORD',{exact:true}).first().waitFor();await context.setOffline(false);await browser.close();console.log(`${name} functional/certification/offline PASS`);}
for(const [name,type] of [['Chromium',chromium],['WebKit',webkit]]){await migrationGate(type,name);await appGate(type,name);}
