import {APP,LIMITS} from '../src/config.js';
import {validateRecognitionEnvelope} from '../src/validators.js';
import {sha256Hex,signEnvelope} from './core.mjs';
import {callProvider} from './providers.mjs';

const JSON_HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
const ID_RE=/^[A-Za-z0-9._-]{8,96}$/;const SHA_RE=/^[a-f0-9]{64}$/i;const te=new TextEncoder(),td=new TextDecoder();
const json=(body,status=200,headers={})=>new Response(JSON.stringify(body),{status,headers:{...JSON_HEADERS,...headers}});
function exactKeys(value,allowed){return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).every(k=>allowed.has(k));}
function validPublicJwk(jwk){return exactKeys(jwk,new Set(['key_ops','ext','kty','x','y','crv']))&&jwk.kty==='EC'&&jwk.crv==='P-256'&&typeof jwk.x==='string'&&typeof jwk.y==='string'&&jwk.x.length<128&&jwk.y.length<128;}
function cors(env,request){const origin=request.headers.get('origin')||'';if(origin!==env.RECORD_ALLOWED_ORIGIN)return null;return {'access-control-allow-origin':origin,'vary':'Origin','access-control-allow-headers':'content-type,x-record-device,x-record-timestamp,x-record-nonce,x-record-body-sha256,x-record-signature,x-record-idempotency-key','access-control-allow-methods':'POST,OPTIONS'};}
function securityStub(env){if(!env.RECORD_SECURITY?.idFromName||!env.RECORD_SECURITY?.get)throw new Error('RECORD_SECURITY Durable Object binding is required.');return env.RECORD_SECURITY.get(env.RECORD_SECURITY.idFromName('record-security-v3'));}
async function securityCall(env,path,body){return securityStub(env).fetch(new Request(`https://record-security.internal${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}));}
function unpack(bytes){if(bytes.length<5)throw new Error('request-truncated');const n=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getUint32(0,false);if(n<2||n>64*1024||4+n>=bytes.length)throw new Error('metadata-length');let metadata;try{metadata=JSON.parse(td.decode(bytes.subarray(4,4+n)));}catch{throw new Error('metadata-json');}return {metadata,imageBytes:bytes.subarray(4+n)};}

export function validateRecognitionMetadata(input,headerIdempotency){
  if(!exactKeys(input,new Set(['schema','requestId','gameId','pageId','sourceSha256','runSequence','runKind','supersedesRequestId','derivedAsset','idempotencyKey'])))throw new Error('request-fields');if(input.schema!=='record-recognition-request/2')throw new Error('request-schema');for(const v of [input.requestId,input.gameId,input.pageId])if(!ID_RE.test(String(v||'')))throw new Error('request-id');if(!SHA_RE.test(String(input.sourceSha256||'')))throw new Error('source-sha');if(!Number.isInteger(input.runSequence)||input.runSequence<1||input.runSequence>100000)throw new Error('run-sequence');if(!['INITIAL','RERUN'].includes(input.runKind))throw new Error('run-kind');if(input.supersedesRequestId!==null&&!ID_RE.test(String(input.supersedesRequestId||'')))throw new Error('supersedes');if(!SHA_RE.test(String(input.idempotencyKey||''))||input.idempotencyKey!==headerIdempotency)throw new Error('idempotency-mismatch');if(!exactKeys(input.derivedAsset,new Set(['id','sha256','mime','width','height','preprocessorVersion'])))throw new Error('derived-fields');const d=input.derivedAsset;if(!ID_RE.test(String(d.id||''))||!SHA_RE.test(String(d.sha256||''))||d.mime!=='image/jpeg'||!Number.isInteger(d.width)||!Number.isInteger(d.height)||d.width<1||d.height<1||d.width*d.height>LIMITS.processingPixels||d.preprocessorVersion!==APP.preprocessorVersion)throw new Error('derived-invalid');return true;
}

async function register(request,env,corsHeaders){
  const text=await request.text();if(te.encode(text).length>16*1024)return json({error:'body-too-large'},413,corsHeaders);let body;try{body=JSON.parse(text);}catch{return json({error:'invalid-json'},400,corsHeaders);}if(!exactKeys(body,new Set(['deviceId','publicJwk','bootstrapTokenId','bootstrapSecret']))||!ID_RE.test(String(body.deviceId||''))||!ID_RE.test(String(body.bootstrapTokenId||''))||!validPublicJwk(body.publicJwk)||typeof body.bootstrapSecret!=='string'||body.bootstrapSecret.length>512)return json({error:'invalid-request'},400,corsHeaders);
  const sec=await securityCall(env,'/register',{...body,expectedTokenId:env.RECORD_BOOTSTRAP_TOKEN_ID,expectedSecret:env.RECORD_BOOTSTRAP_SECRET,ip:request.headers.get('cf-connecting-ip')||'unknown',limit:Number(env.RECORD_REGISTRATION_PER_MINUTE||5)});const out=await sec.json();if(!sec.ok)return json(out,sec.status,corsHeaders);return json({...out,keyId:env.RECORD_GATEWAY_KEY_ID,gatewayPublicJwk:JSON.parse(env.RECORD_GATEWAY_PUBLIC_JWK)},200,corsHeaders);
}

async function recognize(request,env,corsHeaders){
  const contentType=(request.headers.get('content-type')||'').split(';')[0].trim().toLowerCase();if(contentType!=='application/octet-stream')return json({error:'content-type'},415,corsHeaders);const declaredLen=Number(request.headers.get('content-length')||0);if(declaredLen>LIMITS.gatewayBodyBytes)return json({error:'body-too-large'},413,corsHeaders);
  const bytes=new Uint8Array(await request.arrayBuffer());if(bytes.length>LIMITS.gatewayBodyBytes)return json({error:'body-too-large'},413,corsHeaders);let metadata,imageBytes;try{({metadata,imageBytes}=unpack(bytes));validateRecognitionMetadata(metadata,request.headers.get('x-record-idempotency-key'));}catch(error){return json({error:'invalid-request',reason:String(error?.message||error)},400,corsHeaders);}if(imageBytes.length<32||imageBytes.length>LIMITS.gatewayBodyBytes)return json({error:'image-size'},400,corsHeaders);if((await sha256Hex(imageBytes)).toLowerCase()!==metadata.derivedAsset.sha256.toLowerCase())return json({error:'derived-digest-mismatch'},400,corsHeaders);
  const descriptor={deviceId:request.headers.get('x-record-device'),timestamp:request.headers.get('x-record-timestamp'),nonce:request.headers.get('x-record-nonce'),bodyHash:request.headers.get('x-record-body-sha256'),signature:request.headers.get('x-record-signature')};if((await sha256Hex(bytes)).toLowerCase()!==String(descriptor.bodyHash||'').toLowerCase())return json({error:'body-hash'},401,corsHeaders);
  const binding={requestId:metadata.requestId,gameId:metadata.gameId,pageId:metadata.pageId,sourceSha256:metadata.sourceSha256,derivedSha256:metadata.derivedAsset.sha256,runSequence:metadata.runSequence,runKind:metadata.runKind,supersedesRequestId:metadata.supersedesRequestId};const auth=await securityCall(env,'/authorize',{descriptor,idempotencyKey:metadata.idempotencyKey,binding,minuteLimit:Number(env.RECORD_REQUESTS_PER_MINUTE||10),dailyLimit:Number(env.RECORD_DAILY_REQUEST_LIMIT||100)});let authBody=await auth.json();if(!auth.ok)return json(authBody,auth.status,corsHeaders);if(authBody.cached){try{return new Response(authBody.response,{status:200,headers:{...JSON_HEADERS,...corsHeaders}});}catch{return json({error:'cached-response-invalid'},500,corsHeaders);}}
  let raw,signed;try{
    raw=await callProvider({metadata,imageBytes},env);if(raw?.correctMove!==undefined)throw new Error('provider-attempted-authority');const envelope={schema:APP.recognitionEnvelopeSchema,requestId:metadata.requestId,gameId:metadata.gameId,pageId:metadata.pageId,sourceSha256:metadata.sourceSha256,runSequence:metadata.runSequence,supersedesRequestId:metadata.supersedesRequestId,derivedAsset:metadata.derivedAsset,provider:raw.provider,layout:raw.layout,cells:raw.cells||[],metadataObservations:raw.metadataObservations||[],warnings:raw.warnings||[],gateway:{build:'record-gateway/0.3.2',keyId:env.RECORD_GATEWAY_KEY_ID,signedAt:new Date().toISOString()},signature:''};validateRecognitionEnvelope(envelope);signed=await signEnvelope(envelope,JSON.parse(env.RECORD_GATEWAY_PRIVATE_JWK));validateRecognitionEnvelope(signed);
  }catch(error){await securityCall(env,'/fail',{deviceId:descriptor.deviceId,idempotencyKey:metadata.idempotencyKey,bindingHash:authBody.bindingHash,reservationId:authBody.reservationId}).catch(()=>{});return json({error:'provider-failure',reason:String(error?.message||error).slice(0,200)},502,corsHeaders);}
  const responseText=JSON.stringify(signed),complete=await securityCall(env,'/complete',{deviceId:descriptor.deviceId,idempotencyKey:metadata.idempotencyKey,bindingHash:authBody.bindingHash,reservationId:authBody.reservationId,response:responseText});if(!complete.ok)return json({error:'idempotency-completion-failed'},500,corsHeaders);return new Response(responseText,{status:200,headers:{...JSON_HEADERS,...corsHeaders}});
}

export default {async fetch(request,env){const corsHeaders=cors(env,request);if(!corsHeaders)return json({error:'origin-not-allowed'},403);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:corsHeaders});if(request.method!=='POST')return json({error:'method-not-allowed'},405,corsHeaders);const path=new URL(request.url).pathname;if(path==='/register')return register(request,env,corsHeaders);if(path==='/recognize')return recognize(request,env,corsHeaders);return json({error:'not-found'},404,corsHeaders);}};
