import test from 'node:test';
import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
if(!globalThis.crypto)globalThis.crypto=webcrypto;
import worker,{validateRecognitionMetadata} from '../gateway/worker.js';
import {RecordSecurityCoordinator} from '../gateway/security-do.js';
import {sha256Hex,stableStringify,bytesToB64,signEnvelope,verifyRequestSignatureBytes} from '../gateway/core.mjs';
import {packRecognitionRequest} from '../src/recognition.js';
import {APP} from '../src/config.js';
const te=new TextEncoder();
class MemoryStorage{constructor(){this.map=new Map();}async get(k){return this.map.get(k)??null;}async put(k,v){this.map.set(k,structuredClone(v));}async delete(k){this.map.delete(k);}async transaction(fn){return fn(this);}}
class SecurityBinding{constructor(coordinator){this.coordinator=coordinator;}idFromName(name){return name;}get(){return {fetch:req=>this.coordinator.fetch(req)};}}
async function keyPair(){const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);return {pair,pub:await crypto.subtle.exportKey('jwk',pair.publicKey),priv:await crypto.subtle.exportKey('jwk',pair.privateKey)};}
async function signedHeaders({privateKey,deviceId,body,idempotencyKey,nonce=`nonce-${crypto.randomUUID()}`}){const timestamp=new Date().toISOString(),bodyHash=await sha256Hex(body),message=stableStringify({bodyHash,deviceId,nonce,timestamp}),sig=bytesToB64(new Uint8Array(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},privateKey,te.encode(message))));return {'content-type':'application/octet-stream','origin':'https://record.example.test','x-record-device':deviceId,'x-record-timestamp':timestamp,'x-record-nonce':nonce,'x-record-body-sha256':bodyHash,'x-record-signature':sig,'x-record-idempotency-key':idempotencyKey};}
async function fixture(){const device=await keyPair(),gateway=await keyPair(),storage=new MemoryStorage(),coordinator=new RecordSecurityCoordinator({storage},{}),token='bootstrap-token-0001',secret='this-is-a-long-random-bootstrap-secret-0001';const env={RECORD_ALLOWED_ORIGIN:'https://record.example.test',RECORD_BOOTSTRAP_TOKEN_ID:token,RECORD_BOOTSTRAP_SECRET:secret,RECORD_GATEWAY_PRIVATE_JWK:JSON.stringify(gateway.priv),RECORD_GATEWAY_PUBLIC_JWK:JSON.stringify(gateway.pub),RECORD_GATEWAY_KEY_ID:'gateway-key-0001',RECORD_DAILY_REQUEST_LIMIT:'20',RECORD_REQUESTS_PER_MINUTE:'10',RECORD_REGISTRATION_PER_MINUTE:'5',RECORD_PROVIDER_MODE:'fixture',RECORD_SECURITY:new SecurityBinding(coordinator)};return {env,device,gateway,storage,coordinator,deviceId:'device-00000001',token,secret};}
function metadata({requestId='request-00000001',gameId='game-0000000001',pageId='page-0000000001',sourceSha='a'.repeat(64),derivedSha='b'.repeat(64),idem='c'.repeat(64),runSequence=1,runKind='INITIAL',supersedesRequestId=null}={}){return {schema:'record-recognition-request/2',requestId,gameId,pageId,sourceSha256:sourceSha,runSequence,runKind,supersedesRequestId,derivedAsset:{id:'asset-000000001',sha256:derivedSha,mime:'image/jpeg',width:800,height:1200,preprocessorVersion:APP.preprocessorVersion},idempotencyKey:idem};}
async function registerViaWorker(f){const req=new Request('https://gateway.example/register',{method:'POST',headers:{origin:f.env.RECORD_ALLOWED_ORIGIN,'content-type':'application/json','cf-connecting-ip':'192.0.2.1'},body:JSON.stringify({deviceId:f.deviceId,publicJwk:f.device.pub,bootstrapTokenId:f.token,bootstrapSecret:f.secret})});return worker.fetch(req,f.env);}

test('gateway verifies signed binary device request and rejects body mutation',async()=>{const d=await keyPair(),body=te.encode('binary-body'),deviceId='device-00000001',timestamp=new Date().toISOString(),nonce='nonce-00000001',bodyHash=await sha256Hex(body),message=stableStringify({bodyHash,deviceId,nonce,timestamp}),signature=bytesToB64(new Uint8Array(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},d.pair.privateKey,te.encode(message)))),headers=new Headers({'x-record-device':deviceId,'x-record-timestamp':timestamp,'x-record-nonce':nonce,'x-record-body-sha256':bodyHash,'x-record-signature':signature});assert.equal((await verifyRequestSignatureBytes({headers,bodyBytes:body,publicJwk:d.pub})).ok,true);assert.equal((await verifyRequestSignatureBytes({headers,bodyBytes:te.encode('changed'),publicJwk:d.pub})).ok,false);});
test('gateway envelope signing produces signature',async()=>{const g=await keyPair(),out=await signEnvelope({a:1,signature:''},g.priv);assert.ok(out.signature.length>20);});
test('bootstrap capability is one-use and cannot overwrite registered device key',async()=>{const f=await fixture();assert.equal((await registerViaWorker(f)).status,200);const other=await keyPair();const req2=new Request('https://gateway.example/register',{method:'POST',headers:{origin:f.env.RECORD_ALLOWED_ORIGIN,'content-type':'application/json','cf-connecting-ip':'192.0.2.1'},body:JSON.stringify({deviceId:f.deviceId,publicJwk:other.pub,bootstrapTokenId:f.token,bootstrapSecret:f.secret})});const second=await worker.fetch(req2,f.env);assert.equal(second.status,409);const stored=await f.storage.get(`device:${f.deviceId}`);assert.deepEqual(stored.publicJwk,f.device.pub);});
test('gateway signed recognition is digest-bound and exact retry is idempotent',async()=>{const f=await fixture();assert.equal((await registerViaWorker(f)).status,200);const image=te.encode('derived-image-bytes-long-enough-for-gateway-000000000000'),derivedHash=await sha256Hex(image),idem='c'.repeat(64),meta=metadata({derivedSha:derivedHash,idem}),body=packRecognitionRequest(meta,image),headers=await signedHeaders({privateKey:f.device.pair.privateKey,deviceId:f.deviceId,body,idempotencyKey:idem});const res=await worker.fetch(new Request('https://gateway.example/recognize',{method:'POST',headers,body}),f.env);assert.equal(res.status,200);const out=await res.json();assert.equal(out.schema,APP.recognitionEnvelopeSchema);assert.equal(out.requestId,meta.requestId);assert.equal(out.derivedAsset.sha256,derivedHash);assert.ok(out.signature.length>20);const headers2=await signedHeaders({privateKey:f.device.pair.privateKey,deviceId:f.deviceId,body,idempotencyKey:idem});const retry=await worker.fetch(new Request('https://gateway.example/recognize',{method:'POST',headers:headers2,body}),f.env);assert.equal(retry.status,200);assert.deepEqual(await retry.json(),out);});
test('deliberate rerun has a new idempotency identity and returns the new request binding',async()=>{const f=await fixture();assert.equal((await registerViaWorker(f)).status,200);const image=te.encode('derived-image-bytes-long-enough-for-gateway-111111111111'),derivedHash=await sha256Hex(image),firstIdem='d'.repeat(64),firstMeta=metadata({derivedSha:derivedHash,idem:firstIdem}),firstBody=packRecognitionRequest(firstMeta,image),firstHeaders=await signedHeaders({privateKey:f.device.pair.privateKey,deviceId:f.deviceId,body:firstBody,idempotencyKey:firstIdem});assert.equal((await worker.fetch(new Request('https://gateway.example/recognize',{method:'POST',headers:firstHeaders,body:firstBody}),f.env)).status,200);const rerunIdem='e'.repeat(64),rerunMeta=metadata({requestId:'request-00000002',derivedSha:derivedHash,idem:rerunIdem,runSequence:2,runKind:'RERUN',supersedesRequestId:firstMeta.requestId}),rerunBody=packRecognitionRequest(rerunMeta,image),rerunHeaders=await signedHeaders({privateKey:f.device.pair.privateKey,deviceId:f.deviceId,body:rerunBody,idempotencyKey:rerunIdem});const rr=await worker.fetch(new Request('https://gateway.example/recognize',{method:'POST',headers:rerunHeaders,body:rerunBody}),f.env);assert.equal(rr.status,200);const out=await rr.json();assert.equal(out.requestId,rerunMeta.requestId);assert.equal(out.runSequence,2);assert.equal(out.supersedesRequestId,firstMeta.requestId);});
test('gateway rejects image bytes that do not match declared derivative digest',async()=>{const f=await fixture();assert.equal((await registerViaWorker(f)).status,200);const image=te.encode('derived-image-bytes-long-enough-for-gateway-222222222222'),idem='f'.repeat(64),meta=metadata({requestId:'request-00000003',derivedSha:'e'.repeat(64),idem}),body=packRecognitionRequest(meta,image),headers=await signedHeaders({privateKey:f.device.pair.privateKey,deviceId:f.deviceId,body,idempotencyKey:idem});const res=await worker.fetch(new Request('https://gateway.example/recognize',{method:'POST',headers,body}),f.env);assert.equal(res.status,400);assert.equal((await res.json()).error,'derived-digest-mismatch');});
test('recognition metadata validator rejects authority fields and idempotency mismatch',()=>{const base=metadata({idem:'a'.repeat(64)});assert.doesNotThrow(()=>validateRecognitionMetadata(base,'a'.repeat(64)));assert.throws(()=>validateRecognitionMetadata({...base,correctMove:'e4'},'a'.repeat(64)),/request-fields/);assert.throws(()=>validateRecognitionMetadata(base,'b'.repeat(64)),/idempotency/);});
test('security coordinator namespaces idempotency by device and full binding',async()=>{const f=await fixture(),d2=await keyPair();async function directRegister(deviceId,pub,token,secret){const r=await f.coordinator.fetch(new Request('https://x/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({deviceId,publicJwk:pub,bootstrapTokenId:token,bootstrapSecret:secret,expectedTokenId:token,expectedSecret:secret,ip:'x',limit:10})}));assert.equal(r.status,200);}await directRegister(f.deviceId,f.device.pub,'token-one-0001','secret-secret-secret-secret-0001');await directRegister('device-00000002',d2.pub,'token-two-0002','secret-secret-secret-secret-0002');async function auth(deviceId,pair,idem,binding,nonce){const bodyHash='a'.repeat(64),timestamp=new Date().toISOString(),message=stableStringify({bodyHash,deviceId,nonce,timestamp}),signature=bytesToB64(new Uint8Array(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},pair.privateKey,te.encode(message)))),descriptor={deviceId,timestamp,nonce,bodyHash,signature};return f.coordinator.fetch(new Request('https://x/authorize',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({descriptor,idempotencyKey:idem,binding,minuteLimit:10,dailyLimit:20})}));}const idem='9'.repeat(64),binding={requestId:'request-00000001',gameId:'game-0000000001',pageId:'page-0000000001',sourceSha256:'1'.repeat(64),derivedSha256:'2'.repeat(64),runSequence:1,runKind:'INITIAL',supersedesRequestId:null};assert.equal((await auth(f.deviceId,f.device.pair,idem,binding,'nonce-device1-0001')).status,200);assert.equal((await auth('device-00000002',d2.pair,idem,binding,'nonce-device2-0001')).status,200);const changed={...binding,pageId:'page-9999999999'};const conflict=await auth(f.deviceId,f.device.pair,idem,changed,'nonce-device1-0002');assert.equal(conflict.status,409);assert.equal((await conflict.json()).error,'idempotency-binding-mismatch');});

test('OpenAI Responses adapter is explicitly stateless at API storage boundary',async()=>{
  const source=await import('node:fs/promises').then(fs=>fs.readFile(new URL('../gateway/providers.mjs',import.meta.url),'utf8'));
  assert.match(source,/store:false/);
  assert.match(source,/type:'json_schema'/);
  assert.match(source,/input_image/);
});
