import {APP,LIMITS} from './config.js';
import {ERR, RecordError} from './errors.js';
import {createZip,parseZipStore,textMember} from './zip.js';
import {sha256Bytes,sha256Text,stableStringify,timingSafeEqualText,uuid} from './crypto.js';
import {canonicalCertificationRecordFromDescriptors,gamePgn,observationDescriptorsForMoves,sourceDescriptors,verifyCertification,verifySourceIntegrity} from './record.js';
import {validateAuditEvent,validateCapsuleManifest,validateCapsuleSourceDescriptor,validateGame,validateRecognitionEnvelope,validateReconstructionRun,validateSourcePage} from './validators.js';
import {verifyGatewaySignature} from './device-auth.js';

const ext=m=>m==='image/png'?'png':m==='image/webp'?'webp':'jpg',encoder=new TextEncoder(),decoder=new TextDecoder('utf-8',{fatal:true});
async function descriptors(files){const out=[];for(const f of files){const data=f.data instanceof Uint8Array?f.data:encoder.encode(String(f.data));out.push({path:f.name,size:data.length,sha256:await sha256Bytes(data)});}return out.sort((a,b)=>a.path.localeCompare(b.path));}
function sourcePath(source){return `source/page-${String(source.order+1).padStart(3,'0')}.${ext(source.mime)}`;}
function derivedPath(asset){return `derived/${asset.id}.${ext(asset.mime)}`;}
function pseudoPage(source,data){const t='2000-01-01T00:00:00.000Z';return {id:source.id,schema:APP.sourceSchema,gameId:'capsule-verification',order:source.order,createdAt:t,updatedAt:t,name:`page-${source.order+1}`,declaredMime:source.mime,detectedMime:source.mime,mime:source.mime,animated:false,size:source.size,width:source.width,height:source.height,sha256:source.sha256,blob:new Blob([data],{type:source.mime})};}
async function rehashDerived(assets){for(const a of assets){const data=new Uint8Array(await a.blob.arrayBuffer()),hash=await sha256Bytes(data);if(data.length!==a.size||!timingSafeEqualText(hash,a.sha256))throw new RecordError(ERR.EXP_CAPSULE,`Derived asset digest mismatch before export: ${a.id}`);}return assets;}

export async function buildCapsule({game,pages,derivedAssets=[],observations=[],auditEvents=[],reconstructionRuns=[],trustContext={}}){
  const cert=await verifyCertification(game,pages,observations);if(cert.status!=='VALID')throw new RecordError(ERR.EXP_CAPSULE,`Capsule export requires a verified certification; status=${cert.status}.`);
  const ordered=await verifySourceIntegrity(pages);await rehashDerived(derivedAssets);observations.forEach(validateRecognitionEnvelope);auditEvents.forEach(validateAuditEvent);reconstructionRuns.forEach(validateReconstructionRun);
  const sources=sourceDescriptors(ordered),sourceById=new Map(sources.map(s=>[s.id,s])),derivedById=new Map(derivedAssets.filter(a=>a.purpose==='recognition').map(a=>[a.id,a]));
  for(const o of observations){const source=sourceById.get(o.pageId);if(!source||!timingSafeEqualText(source.sha256,o.sourceSha256))throw new RecordError(ERR.EXP_CAPSULE,'Recognition observation is not bound to a Capsule source page.');const derived=derivedById.get(o.derivedAsset.id);if(!derived||!timingSafeEqualText(derived.sha256,o.derivedAsset.sha256)||derived.sourcePageId!==o.pageId)throw new RecordError(ERR.EXP_CAPSULE,'Recognition observation is not bound to a supplied derived asset.');}
  // Resolve every move observation reference before any bytes are emitted.
  await observationDescriptorsForMoves(game,ordered,observations);
  const auditSorted=[...auditEvents].sort((a,b)=>a.timestamp.localeCompare(b.timestamp)||a.id.localeCompare(b.id)),auditRoot=await sha256Text(stableStringify(auditSorted));const record={schema:'record-export/3',canonicalRecordHash:cert.canonicalHash,observationRoot:cert.observationRoot,auditRoot,sources,game};
  const files=[{name:'game.pgn',data:gamePgn(game)},{name:'record.json',data:JSON.stringify(record,null,2)},{name:'audit/events.json',data:JSON.stringify(auditSorted,null,2)},{name:'reconstruction/runs.json',data:JSON.stringify(reconstructionRuns,null,2)}];
  for(const p of ordered)files.push({name:sourcePath(p),data:new Uint8Array(await p.blob.arrayBuffer())});for(const a of derivedAssets.filter(x=>x.purpose==='recognition'))files.push({name:derivedPath(a),data:new Uint8Array(await a.blob.arrayBuffer())});for(const o of observations)files.push({name:`observations/${o.requestId}.recognition.json`,data:JSON.stringify(o,null,2)});
  files.push({name:'derived/README.txt',data:'Derived assets are inference inputs. Original source bytes in source/ remain the evidentiary source. Recognition observations are untrusted observations, never historical authority. Original source photos are intentionally preserved exactly and may contain embedded image metadata.\n'});
  const desc=await descriptors(files),contentRoot=await sha256Text(stableStringify(desc)),manifest={schema:APP.capsuleSchema,capsuleInstanceId:uuid(),createdAt:new Date().toISOString(),canonicalRecordHash:cert.canonicalHash,certificationFingerprint:game.certification.canonicalHash,observationRoot:cert.observationRoot,auditRoot,capsuleContentRoot:contentRoot,files:desc,signatures:[]};validateCapsuleManifest(manifest);files.push({name:'manifest.json',data:JSON.stringify(manifest,null,2)});
  const bytes=createZip(files,{deterministic:true,maxBytes:LIMITS.capsuleArchiveBytes});await verifyCapsule(bytes,{trustContext,requireTrustedObservations:observations.some(o=>!!o.signature)});return {bytes,manifest};
}

async function classifyObservationTrust(env,trustContext={}){if(!env.signature)return env.gateway.keyId==='UNSIGNED_FIXTURE'?'UNSIGNED_FIXTURE':'IMPORTED_UNVERIFIED';const jwk=trustContext.gatewayKeys?.[env.gateway.keyId]||null;if(!jwk)return 'UNKNOWN_KEY';return await verifyGatewaySignature(env,jwk)?'SIGNED_VERIFIED':'SIGNATURE_INVALID';}

export async function verifyCapsule(bytes,{trustContext={},requireTrustedObservations=false}={}){
  const files=parseZipStore(bytes,{maxBytes:LIMITS.capsuleArchiveBytes});let manifest,record;try{manifest=JSON.parse(textMember(files,'manifest.json'));record=JSON.parse(textMember(files,'record.json'));}catch(error){throw new RecordError(ERR.EXP_CAPSULE,'Capsule JSON could not be parsed.',{cause:String(error)});}validateCapsuleManifest(manifest);
  const expectedMembers=new Set(['manifest.json',...manifest.files.map(d=>d.path)]);if(files.size!==expectedMembers.size||[...files.keys()].some(name=>!expectedMembers.has(name)))throw new RecordError(ERR.EXP_CAPSULE,'Capsule contains an unmanifested or unexpected member.');const actual=[];for(const d of manifest.files){const data=files.get(d.path);if(!data)throw new RecordError(ERR.EXP_CAPSULE,`Capsule member missing: ${d.path}`);const hash=await sha256Bytes(data);if(!timingSafeEqualText(hash,d.sha256)||data.length!==d.size)throw new RecordError(ERR.EXP_CAPSULE,`Capsule member integrity failed: ${d.path}`);actual.push({path:d.path,size:data.length,sha256:hash});}actual.sort((a,b)=>a.path.localeCompare(b.path));if(!timingSafeEqualText(await sha256Text(stableStringify(actual)),manifest.capsuleContentRoot))throw new RecordError(ERR.EXP_CAPSULE,'Capsule content root mismatch.');
  if(!record||record.schema!=='record-export/3'||!Array.isArray(record.sources))throw new RecordError(ERR.EXP_CAPSULE,'Capsule record export schema is invalid.');validateGame(record.game);const sources=[...record.sources].sort((a,b)=>a.order-b.order);sources.forEach(validateCapsuleSourceDescriptor);const sourceIds=new Set(),pages=[];
  for(const source of sources){if(sourceIds.has(source.id))throw new RecordError(ERR.EXP_CAPSULE,'Duplicate Capsule source ID.');sourceIds.add(source.id);const path=sourcePath(source),data=files.get(path);if(!data)throw new RecordError(ERR.EXP_CAPSULE,`Source member missing: ${path}`);const hash=await sha256Bytes(data);if(data.length!==source.size||!timingSafeEqualText(hash,source.sha256))throw new RecordError(ERR.EXP_CAPSULE,`Source descriptor mismatch: ${path}`);const page=pseudoPage(source,data);page.gameId=record.game.id;validateSourcePage(page);pages.push(page);}
  // The interoperability PGN must be exactly the canonical PGN derived from the evidentiary record.
  const actualPgn=decoder.decode(files.get('game.pgn')||new Uint8Array());const expectedPgn=gamePgn(record.game);if(actualPgn!==expectedPgn)throw new RecordError(ERR.EXP_CAPSULE,'game.pgn is not semantically/canonically identical to record.json.');
  const observations=[],trust=[];for(const [name,data] of files.entries())if(name.startsWith('observations/')){let env;try{env=JSON.parse(decoder.decode(data));}catch{throw new RecordError(ERR.EXP_CAPSULE,`Recognition observation is invalid JSON: ${name}`);}validateRecognitionEnvelope(env);const source=sources.find(s=>s.id===env.pageId);if(!source||!timingSafeEqualText(source.sha256,env.sourceSha256))throw new RecordError(ERR.EXP_CAPSULE,`Recognition observation source binding failed: ${name}`);const dpath=`derived/${env.derivedAsset.id}.${ext(env.derivedAsset.mime)}`,derived=files.get(dpath);if(!derived)throw new RecordError(ERR.EXP_CAPSULE,`Recognition derived asset missing: ${dpath}`);if(!timingSafeEqualText(await sha256Bytes(derived),env.derivedAsset.sha256))throw new RecordError(ERR.EXP_CAPSULE,`Recognition derived-asset binding failed: ${name}`);const classification=await classifyObservationTrust(env,trustContext);if(classification==='SIGNATURE_INVALID'||(requireTrustedObservations&&!['SIGNED_VERIFIED','UNSIGNED_FIXTURE'].includes(classification)))throw new RecordError(ERR.EXP_CAPSULE,`Recognition observation trust verification failed: ${name} (${classification})`);observations.push(env);trust.push({requestId:env.requestId,keyId:env.gateway.keyId,classification});}
  const obsDescriptors=await observationDescriptorsForMoves(record.game,pages,observations),observationRoot=await sha256Text(stableStringify(obsDescriptors));if(!timingSafeEqualText(observationRoot,record.observationRoot)||!timingSafeEqualText(observationRoot,manifest.observationRoot)||!timingSafeEqualText(observationRoot,record.game.certification?.observationRoot||''))throw new RecordError(ERR.EXP_CAPSULE,'Capsule observation root mismatch.');
  const canonical=await sha256Text(stableStringify(canonicalCertificationRecordFromDescriptors(record.game,sources,obsDescriptors)));if(!timingSafeEqualText(canonical,record.canonicalRecordHash)||!timingSafeEqualText(canonical,manifest.canonicalRecordHash)||!timingSafeEqualText(canonical,manifest.certificationFingerprint)||!timingSafeEqualText(canonical,record.game.certification?.canonicalHash||''))throw new RecordError(ERR.EXP_CAPSULE,'Capsule certification canonical hash mismatch.');
  if(!record.game.certification||record.game.certification.recordRevision!==record.game.revision||record.game.certification.sourceRevision!==record.game.sourceRevision)throw new RecordError(ERR.EXP_CAPSULE,'Capsule certification revision state is invalid.');
  let audits;try{audits=JSON.parse(textMember(files,'audit/events.json'));}catch{throw new RecordError(ERR.EXP_CAPSULE,'Capsule audit stream is invalid JSON.');}if(!Array.isArray(audits))throw new RecordError(ERR.EXP_CAPSULE,'Capsule audit stream must be an array.');audits.forEach(validateAuditEvent);const auditRoot=await sha256Text(stableStringify([...audits].sort((a,b)=>a.timestamp.localeCompare(b.timestamp)||a.id.localeCompare(b.id))));if(!timingSafeEqualText(auditRoot,record.auditRoot)||!timingSafeEqualText(auditRoot,manifest.auditRoot))throw new RecordError(ERR.EXP_CAPSULE,'Capsule audit root mismatch.');
  let runs;try{runs=JSON.parse(textMember(files,'reconstruction/runs.json'));}catch{throw new RecordError(ERR.EXP_CAPSULE,'Capsule reconstruction stream is invalid JSON.');}if(!Array.isArray(runs))throw new RecordError(ERR.EXP_CAPSULE,'Capsule reconstruction stream must be an array.');runs.forEach(validateReconstructionRun);
  return {valid:true,manifest,game:record.game,sources,observations,observationTrust:trust,auditEvents:audits,reconstructionRuns:runs};
}
